Initial draft converting rocm

diff --git a/Dockerfile-rocm-hpc b/Dockerfile-rocm-hpc
--- a/Dockerfile-rocm-hpc
+++ b/Dockerfile-rocm-hpc
@@ -1,25 +1,48 @@
 ARG BASE_IMAGE
 FROM ${BASE_IMAGE}
 
-RUN apt remove -y openmpi ucx || true
-#Let's remove existing /opt/ompi; and, link to our version.
-RUN rm -rf /opt/ompi 
-RUN ln -s /container/ompi /opt 
-
-RUN rm /etc/apt/sources.list.d/rocm.list
-
-# Copy shell scripts as needed so that a simple change to one of those
-# scripts does not cause this image and all derived images from being
-# completely rebuilt. This can save significant build time, especially for
-# the HPC images.
 ARG SCRIPT_DIR=/tmp/dockerfile_scripts
 RUN mkdir -p ${SCRIPT_DIR}
 
+# Remove the ompi/ucx, etc that is in the base image
+# Seems that the torch installed in the NGC image links against this.
+# Wonder if that will cause problems? We can have it use our OMPI but it
+# also wants libucs, etc, from UCX. The NGC container must be building
+# torch from source and enabling torch distributed with mpi backend.
+#RUN rm -rf /opt/hpcx /usr/local/mpi
+RUN apt remove -y openmpi ucx || true
+
+# Put all HPC related tools we build under /container/hpc so we can
+# have a shared include, lib, bin, etc to simplify our paths and build steps.
+ARG HPC_DIR=/container/hpc
+RUN mkdir -p ${HPC_DIR}/bin && \
+    mkdir -p ${HPC_DIR}/lib && \
+    mkdir -p ${HPC_DIR}/include && \
+    mkdir -p ${HPC_DIR}/share && \
+    ln -s ${HPC_DIR}/lib ${HPC_DIR}/lib64 && \
+    chmod -R go+rX ${HPC_DIR}
+ENV LD_LIBRARY_PATH=$HPC_DIR/lib:$LD_LIBRARY_PATH
+ENV PATH=$HPC_DIR/bin:$PATH
+
+# Setup some default env variables. This is for the end user as well
+# as tools we will build since we put include files under HPC_DIR.
+COPY dockerfile_scripts/setup_sh_env.sh ${SCRIPT_DIR}
+RUN ${SCRIPT_DIR}/setup_sh_env.sh
+
+# We run this here even though it might be a repeat from the base image
+# to make sure we have the required bits for building NCCL, libcxi, etc.
 COPY dockerfile_scripts/install_deb_packages.sh ${SCRIPT_DIR}
 RUN ${SCRIPT_DIR}/install_deb_packages.sh
-RUN pip install --upgrade pip
 
-COPY dockerfile_scripts ${SCRIPT_DIR}
+# Should we just use /container as the install dir and put
+# everything (ie, ucx/ofi/ompi/mpich) under /container/{bin|lib}
+# to clean up these arguments?
+# Install Cray CXI headers/lib
+COPY dockerfile_scripts/cray-libs.sh ${SCRIPT_DIR}
+ARG WITH_OFI
+RUN if [ "$WITH_OFI" = "1" ]; then \
+    ${SCRIPT_DIR}/cray-libs.sh ; \
+    fi
 
 ENV PATH="/opt/conda/envs/py_3.8/bin:${PATH}"
 
@@ -29,6 +52,7 @@ ENV PYTHONUNBUFFERED=1 PYTHONFAULTHANDLER=1 PYTHONHASHSEED=0
 
 # Install fixed version of FFI package for Ubuntu 20.04.
 # This is done after above stuff to make sure we get right version.
+COPY dockerfile_scripts/install_package_fixes.sh ${SCRIPT_DIR}
 RUN ${SCRIPT_DIR}/install_package_fixes.sh
 
 RUN apt install rocm-libs 
@@ -43,6 +67,7 @@ ARG MPICH_INSTALL_DIR=/container/mpich
 ARG OFI_INSTALL_DIR=/container/ofi
 ARG OMPI_WITH_CUDA=0
 ARG OMPI_WITH_ROCM=1
+COPY dockerfile_scripts/ompi_rocm.sh ${SCRIPT_DIR}
 RUN if [ "$WITH_MPI" = "1" ]; then ${SCRIPT_DIR}/ompi_rocm.sh "$UBUNTU_VERSION" "$WITH_OFI" "$OMPI_WITH_ROCM" "$WITH_MPICH"; fi
 
 # Make sure OMPI/UCX show up in the right paths
@@ -85,17 +110,6 @@ RUN pip install cloudpickle
 RUN pip install determined && pip uninstall -y determined
 RUN pip install google-auth-oauthlib
 
-
-
-RUN pip install -r ${SCRIPT_DIR}/notebook-requirements.txt && jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
-ENV JUPYTER_CONFIG_DIR=/run/determined/jupyter/config
-ENV JUPYTER_DATA_DIR=/run/determined/jupyter/data
-ENV JUPYTER_RUNTIME_DIR=/run/determined/jupyter/runtime
-
-RUN ${SCRIPT_DIR}/add_det_nobody_user.sh
-RUN ${SCRIPT_DIR}/install_libnss_determined.sh
-RUN ${SCRIPT_DIR}/install_google_cloud_sdk.sh
-
 # google-api-python-client -> google-api-core -> googleapis-common-protos -> protobuf
 # Horovod cannot build with protobuf > 3.20.x
 # latest google-api-python-client requires protobuf >= 3.20.1
@@ -137,9 +151,10 @@ ENV NCCL_LIB_DIR=${HOROVOD_NCCL_HOME}/lib
 ENV HOROVOD_NCCL_LINK=${WITH_OFI:+SHARED}
 ENV LD_LIBRARY_PATH=${WITH_OFI:+$NCCL_LIB_DIR:}$LD_LIBRARY_PATH
 
-RUN if [ "$HOROVOD_PIP" != "0" ]; then pip install "${HOROVOD_PIP}" ; fi
+###RUN if [ "$HOROVOD_PIP" != "0" ]; then pip install "${HOROVOD_PIP}" ; fi
 
 RUN pip uninstall -y tb-nightly tensorboardX
+COPY dockerfile_scripts/additional-requirements-rocm.txt ${SCRIPT_DIR}
 RUN pip install -r ${SCRIPT_DIR}/additional-requirements-rocm.txt
 
 
@@ -151,18 +166,12 @@ ARG INTERNAL_AWS_DS
 ARG INTERNAL_AWS_PATH
 ARG ROCM_DIR=/opt/rocm
 ENV ROCM_DIR $ROCM_DIR
+COPY dockerfile_scripts/build_aws_rocm.sh ${SCRIPT_DIR}
 RUN if [ "$WITH_OFI" = "1" ]; then ${SCRIPT_DIR}/build_aws_rocm.sh "$WITH_OFI" "$WITH_AWS_TRACE" "$WITH_MPICH"; fi
 ENV LD_LIBRARY_PATH=${WITH_OFI:+$AWS_PLUGIN_INSTALL_DIR:}$LD_LIBRARY_PATH
 RUN ldconfig
 
 ENV PATH=$OMPI_PATH_DIR:$OFI_INSTALL_DIR:$PATH
-# Reset entrypoint.
-
-# Set an entrypoint that can scrape up the host libfabric.so and then 
-# run the user command. This is intended to enable performant execution
-# on non-IB systems that have a proprietary libfabric.
-
-RUN mkdir -p /container/bin && cp ${SCRIPT_DIR}/scrape_libs.sh /container/bin
 
 ARG WITH_RCCL=1
 ENV WITH_RCCL=$WITH_RCCL
@@ -175,17 +184,31 @@ ENV DEEPDEEP=1
 
 ARG BASE_IMAGE
 
-RUN if [ "$HOROVOD_PIP" != "0" ]; then if [ ! `echo "$BASE_IMAGE"|grep  rocm6.0` ] ; then pip install "${HOROVOD_PIP}" ; fi ; fi;
+###RUN if [ "$HOROVOD_PIP" != "0" ]; then if [ ! `echo "$BASE_IMAGE"|grep  rocm6.0` ] ; then pip install "${HOROVOD_PIP}" ; fi ; fi;
+#### Try installing Horovod
+###ARG WITH_PT
+###ARG WITH_TF
+###COPY dockerfile_scripts/build_horovod.sh ${SCRIPT_DIR}
+###RUN if [ "$WITH_MPI" = "1" ] ; then \
+###    ${SCRIPT_DIR}/build_horovod.sh "$WITH_PT" "$WITH_TF"; \
+###    fi
 
-RUN if [ -n "$DEEPSPEED_PIP" ]; then DEBIAN_FRONTEND=noninteractive apt-get install -y pdsh libaio-dev&& git clone https://github.com/ROCmSoftwarePlatform/triton.git && cd triton && git checkout triton-mlir && cd python && pip3 install ninja cmake && pip install -e .;fi
-RUN if [ -n "$DEEPSPEED_PIP" ]; then DEBIAN_FRONTEND=noninteractive apt-get install -y pdsh libaio-dev&& python -m pip install  pydantic==1.10.11 && git clone https://github.com/ROCmSoftwarePlatform/DeepSpeed.git && cd DeepSpeed && python3 setup.py  build && python3 setup.py install && python -m deepspeed.env_report; fi
-RUN if [ -n "$DEEPSPEED_PIP" ]; then python -m deepspeed.env_report ; fi
+###RUN if [ -n "$DEEPSPEED_PIP" ]; then DEBIAN_FRONTEND=noninteractive apt-get install -y pdsh libaio-dev&& git clone https://github.com/ROCmSoftwarePlatform/triton.git && cd triton && git checkout triton-mlir && cd python && pip3 install ninja cmake && pip install -e .;fi
+###RUN if [ -n "$DEEPSPEED_PIP" ]; then DEBIAN_FRONTEND=noninteractive apt-get install -y pdsh libaio-dev&& python -m pip install  pydantic==1.10.11 && git clone https://github.com/ROCmSoftwarePlatform/DeepSpeed.git && cd DeepSpeed && python3 setup.py  build && python3 setup.py install && python -m deepspeed.env_report; fi
+###RUN if [ -n "$DEEPSPEED_PIP" ]; then python -m deepspeed.env_report ; fi
 
 #MIOPEN_DEBUG_SAVE_TEMP_DIR is required to prevent 
 # PAD-133
 ENV MIOPEN_DEBUG_SAVE_TEMP_DIR=1
 
+# Set an entrypoint that can scrape up the host libfabric.so and then
+# run the user command. This is intended to enable performant execution
+# on non-IB systems that have a proprietary libfabric.
+COPY dockerfile_scripts/scrape_libs.sh ${SCRIPT_DIR}
+RUN mkdir -p /container/bin && \
+    cp ${SCRIPT_DIR}/scrape_libs.sh /container/bin
 ENTRYPOINT ["/container/bin/scrape_libs.sh"]
+
 CMD ["/bin/bash"]
 USER root
 
